# This is a basic workflow to help you get started with Actions

name: ImmortalWrt

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkOut
        uses: actions/checkout@v4
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /etc/apt/sources.list.d
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt/archives/*') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang clangd cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev \
          libssl-dev libtool lld lldb lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 \
          python3 python3-pip python3-ply python3-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig \
          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo timedatectl set-timezone Asia/Singapore
          git clone --depth=1 https://github.com/hanwckf/immortalwrt-mt798x.git openwrt
          df -h
      - name: config
        working-directory: ./openwrt
        run: |
          git clone --depth=1 https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter
          cp ../.config .
          sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          #make defconfig
          make oldconfig
          echo -e "$(nproc) thread compile"
          make download -j$(nproc)
          make -j$(nproc) V=s
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Check space usage
        if: (!cancelled())
        run: df -hT
      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt_${{ env.FILE_DATE }}
          path: |
            openwrt/bin
            openwrt/.config
      
