name: u-boot
on:
  workflow_dispatch:
    inputs:
      soc:
        required: true
        description: SOC/CPU Model
        type: string
        default: mt7981
      board:
        required: true
        description: Router Model Name
        type: choice
        default: newland_nl-wr9103
        options:
          - 'newland_nl-wr9103'
          - 'newland_nl-wr8103'
          - '360t7'
          - 'ax3000t'
          - 'nokia_ea0326gmp'
          - 'abt_asr3000'
          - 'konka_komi-a31'
      multi-layout:
        required: true
        description: Enable Multiple Flash Layout Support
        type: choice
        default: '1'
        options:
          - '0'
          - '1'
      runs-on:
        required: true
        description: Runs on...
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest

jobs:
  ubuntu-build:
    name: Build on ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Get build dept.
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu build-essential flex bison libssl-dev
          git clone --depth=1 https://github.com/hanwckf/bl-mt798x.git .
      - name: Build it
        run: |
          ./build.sh
        env:
          SOC: ${{ inputs.soc }}
          BOARD: ${{ inputs.board }}
          MULTI_LAYOUT: ${{ inputs.multi-layout }}
      - uses: actions/upload-artifact@v4
        with:
          name: Uboot - ${{ inputs.board }} (${{ inputs.soc }})
          path: output/


